#############################################################################
# Makefile for building: SuperMario.app/Contents/MacOS/SuperMario
# Generated by qmake (3.1) (Qt 6.8.2)
# Project:  ../../SuperMario.pro
# Template: app
# Command: /Users/yassintawfik/Qt/6.8.2/macos/bin/qmake -o Makefile ../../SuperMario.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk -mmacosx-version-min=12 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk -mmacosx-version-min=12 -Wall -Wextra $(DEFINES)
INCPATH       = -I../../../SuperMario\ real -I. -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/macx-clang -F/Users/yassintawfik/Qt/6.8.2/macos/lib
QMAKE         = /Users/yassintawfik/Qt/6.8.2/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/yassintawfik/Qt/6.8.2/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/yassintawfik/Qt/6.8.2/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SuperMario1.0.0
DISTDIR = /Users/yassintawfik/Desktop/supermariomohab/SuperMario\ real/build/Qt_6_8_2_for_macOS-Debug/.tmp/SuperMario1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk -mmacosx-version-min=12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/yassintawfik/Qt/6.8.2/macos/lib
LIBS          = $(SUBLIBS) -F/Users/yassintawfik/Qt/6.8.2/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework UniformTypeIdentifiers -framework AGL -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../../Bullet.cpp \
		../../Coin.cpp \
		../../Enemy.cpp \
		../../GameObject.cpp \
		../../Level.cpp \
		../../Mario.cpp \
		../../Obstacle.cpp \
		../../Platform.cpp \
		../../Player.cpp \
		../../PowerUp.cpp \
		../../PrincessPeach.cpp \
		../../main.cpp \
		../../mainwindow.cpp qrc_resources.cpp \
		qrc_Resources3.cpp \
		qrc_homepage.cpp \
		qrc_resources2.cpp \
		moc_Bullet.cpp \
		moc_Enemy.cpp \
		moc_Level.cpp \
		moc_Mario.cpp \
		moc_mainwindow.cpp
OBJECTS       = Bullet.o \
		Coin.o \
		Enemy.o \
		GameObject.o \
		Level.o \
		Mario.o \
		Obstacle.o \
		Platform.o \
		Player.o \
		PowerUp.o \
		PrincessPeach.o \
		main.o \
		mainwindow.o \
		qrc_resources.o \
		qrc_Resources3.o \
		qrc_homepage.o \
		qrc_resources2.o \
		moc_Bullet.o \
		moc_Enemy.o \
		moc_Level.o \
		moc_Mario.o \
		moc_mainwindow.o
DIST          = /Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/spec_pre.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/device_config.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/unix.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/mac.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/macx.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/sanitize.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/gcc-base.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/gcc-base-mac.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/clang.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/clang-mac.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/qconfig.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_ext_freetype.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_ext_libpng.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_ext_openxr_loader.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_charts.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_core.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_core_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_dbus.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_designer.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_gui.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_help.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_help_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsplatform.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labssettings.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_linguist.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_network.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_network_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_opengl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_png_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qml.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlmeta.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3d.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dxr.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_shadertools.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_sql.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_svg.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_testlib.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_tools_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_uitools.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_widgets.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_xml.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/qt_functions.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/qt_config.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/macx-clang/qmake.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/spec_post.prf \
		../../.qmake.stash \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/exclusive_builds.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/sdk.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/toolchain.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/toolchain.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/default_pre.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/default_pre.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/resolve_config.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/default_post.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/default_post.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/objective_c.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/qml_debug.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/mac.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/warn_on.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/permissions.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/qt.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/resources_functions.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/resources.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/moc.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/unix/opengl.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/uic.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/unix/thread.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/qmake_use.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/file_copies.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/rez.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/asset_catalogs.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/testcase_targets.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/exceptions.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/yacc.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/lex.prf \
		../../../../SuperMario.pro ../../Bullet.h \
		../../Coin.h \
		../../Enemy.h \
		../../GameObject.h \
		../../Level.h \
		../../Mario.h \
		../../Obstacle.h \
		../../Platform.h \
		../../Player.h \
		../../PowerUp.h \
		../../PrincessPeach.h \
		../../mainwindow.h ../../Bullet.cpp \
		../../Coin.cpp \
		../../Enemy.cpp \
		../../GameObject.cpp \
		../../Level.cpp \
		../../Mario.cpp \
		../../Obstacle.cpp \
		../../Platform.cpp \
		../../Player.cpp \
		../../PowerUp.cpp \
		../../PrincessPeach.cpp \
		../../main.cpp \
		../../mainwindow.cpp
QMAKE_TARGET  = SuperMario
DESTDIR       = 
TARGET        = SuperMario.app/Contents/MacOS/SuperMario

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 15.4
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/yassintawfik/Desktop/supermariomohab/SuperMario real/build/Qt_6_8_2_for_macOS-Debug/.qmake.stash
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/yassintawfik/Desktop/supermariomohab/SuperMario real/SuperMario.pro


include /Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

SuperMario.app/Contents/MacOS/SuperMario: ui_mainwindow.h $(OBJECTS)  
	@test -d SuperMario.app/Contents/MacOS/ || mkdir -p SuperMario.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../../SuperMario.pro /Users/yassintawfik/Qt/6.8.2/macos/mkspecs/macx-clang/qmake.conf /Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/spec_pre.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/device_config.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/unix.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/mac.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/macx.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/sanitize.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/gcc-base.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/gcc-base-mac.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/clang.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/clang-mac.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/qconfig.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_ext_freetype.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_ext_libpng.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_ext_openxr_loader.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_charts.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_core.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_core_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_dbus.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_designer.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_gui.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_help.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_help_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsplatform.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labssettings.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_linguist.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_network.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_network_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_opengl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_png_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qml.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlmeta.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3d.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dxr.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_shadertools.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_sql.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_svg.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_testlib.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_tools_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_uitools.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_widgets.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_xml.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/qt_functions.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/qt_config.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/macx-clang/qmake.conf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/exclusive_builds.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/sdk.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/toolchain.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/toolchain.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/default_pre.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/default_pre.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/resolve_config.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/default_post.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/default_post.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/objective_c.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/qml_debug.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/mac.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/warn_on.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/permissions.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/qt.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/resources_functions.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/resources.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/moc.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/unix/opengl.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/uic.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/unix/thread.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/qmake_use.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/file_copies.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/rez.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/asset_catalogs.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/testcase_targets.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/exceptions.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/yacc.prf \
		/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/lex.prf \
		../../SuperMario.pro \
		../../resources.qrc \
		../../Resources3.qrc \
		../../homepage.qrc \
		../../resources2.qrc \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Resources/QtGui.prl \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile ../../SuperMario.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/spec_pre.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/device_config.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/unix.conf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/mac.conf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/macx.conf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/sanitize.conf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/gcc-base.conf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/gcc-base-mac.conf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/clang.conf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/common/clang-mac.conf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/qconfig.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_ext_freetype.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_ext_libjpeg.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_ext_libpng.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_ext_openxr_loader.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_charts.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_charts_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_chartsqml.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_chartsqml_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_concurrent.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_core.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_core_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_dbus.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_designer.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_designer_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_example_icons_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_freetype_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_gui.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_gui_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_help.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_help_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsanimation.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsplatform.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsplatform_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labssettings.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_linguist.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimedia.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_network.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_network_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_opengl.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_png_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_printsupport.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qml.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qml_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlcompiler.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlcore.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlls_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlmeta.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlnetwork.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmltest.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3d.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3d_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3deffects.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dparticles.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dutils.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dxr.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick3dxr_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quick_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktimeline.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickvectorimage.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_shadertools.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_shadertools_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_spatialaudio.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_sql.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_sql_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_svg.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_svg_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_testlib.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_tools_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_uitools.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_widgets.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_xml.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_lib_xml_private.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/qt_functions.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/qt_config.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/macx-clang/qmake.conf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/exclusive_builds.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/sdk.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/toolchain.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/toolchain.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/default_pre.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/default_pre.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/resolve_config.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/default_post.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/default_post.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/objective_c.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/qml_debug.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/mac.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/warn_on.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/permissions.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/qt.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/resources_functions.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/resources.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/moc.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/unix/opengl.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/uic.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/unix/thread.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/qmake_use.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/file_copies.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/rez.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/mac/asset_catalogs.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/testcase_targets.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/exceptions.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/yacc.prf:
/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/features/lex.prf:
../../SuperMario.pro:
../../resources.qrc:
../../Resources3.qrc:
../../homepage.qrc:
../../resources2.qrc:
/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Resources/QtGui.prl:
/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../../SuperMario.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

SuperMario.app/Contents/PkgInfo: 
	@test -d SuperMario.app/Contents || mkdir -p SuperMario.app/Contents
	@$(DEL_FILE) SuperMario.app/Contents/PkgInfo
	@echo "APPL????" > SuperMario.app/Contents/PkgInfo
SuperMario.app/Contents/Info.plist: 
	@test -d SuperMario.app/Contents || mkdir -p SuperMario.app/Contents
	@$(DEL_FILE) SuperMario.app/Contents/Info.plist
	@plutil -convert xml1 -o - /Users/yassintawfik/Qt/6.8.2/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,assignmenttt.SuperMario,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},assignmenttt.SuperMario,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,SuperMario,g" -e "s,@LIBRARY@,SuperMario,g" -e "s,\$${EXECUTABLE_NAME},SuperMario,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >SuperMario.app/Contents/Info.plist

all: Makefile \
		SuperMario.app/Contents/PkgInfo \
		SuperMario.app/Contents/Info.plist SuperMario.app/Contents/MacOS/SuperMario

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../resources.qrc ../../Resources3.qrc ../../homepage.qrc ../../resources2.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../Bullet.h ../../Coin.h ../../Enemy.h ../../GameObject.h ../../Level.h ../../Mario.h ../../Obstacle.h ../../Platform.h ../../Player.h ../../PowerUp.h ../../PrincessPeach.h ../../mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents ../../Bullet.cpp ../../Coin.cpp ../../Enemy.cpp ../../GameObject.cpp ../../Level.cpp ../../Mario.cpp ../../Obstacle.cpp ../../Platform.cpp ../../Player.cpp ../../PowerUp.cpp ../../PrincessPeach.cpp ../../main.cpp ../../mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../../mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r SuperMario.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp qrc_Resources3.cpp qrc_homepage.cpp qrc_resources2.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp qrc_Resources3.cpp qrc_homepage.cpp qrc_resources2.cpp
qrc_resources.cpp: ../../resources.qrc \
		/Users/yassintawfik/Qt/6.8.2/macos/libexec/rcc \
		../../level_1.png
	/Users/yassintawfik/Qt/6.8.2/macos/libexec/rcc -name resources --no-zstd ../../resources.qrc -o qrc_resources.cpp

qrc_Resources3.cpp: ../../Resources3.qrc \
		/Users/yassintawfik/Qt/6.8.2/macos/libexec/rcc \
		../../m1L.png \
		../../mCoin.png \
		../../mJ1L.png \
		../../m5R.png \
		../../m2R.png \
		../../m4R.png \
		../../L1C.png \
		../../m1R.png \
		../../m6R.png \
		../../m6L.png \
		../../m4L.png \
		../../m3L.png \
		../../mJ2L.png \
		../../mJ1R.png \
		../../m3R.png \
		../../mJ2R.png \
		../../m7L.png \
		../../m5L.png \
		../../m2L.png \
		../../m7R.png
	/Users/yassintawfik/Qt/6.8.2/macos/libexec/rcc -name Resources3 --no-zstd ../../Resources3.qrc -o qrc_Resources3.cpp

qrc_homepage.cpp: ../../homepage.qrc \
		/Users/yassintawfik/Qt/6.8.2/macos/libexec/rcc \
		../../level_1_hp.png
	/Users/yassintawfik/Qt/6.8.2/macos/libexec/rcc -name homepage --no-zstd ../../homepage.qrc -o qrc_homepage.cpp

qrc_resources2.cpp: ../../resources2.qrc \
		/Users/yassintawfik/Qt/6.8.2/macos/libexec/rcc \
		../../m6.png \
		../../m7.png \
		../../m1.png \
		../../m2.png \
		../../m10.png \
		../../m5.png \
		../../m8.png \
		../../m4.png \
		../../m3.png \
		../../m9.png
	/Users/yassintawfik/Qt/6.8.2/macos/libexec/rcc -name resources2 --no-zstd ../../resources2.qrc -o qrc_resources2.cpp

compiler_moc_header_make_all: moc_Bullet.cpp moc_Enemy.cpp moc_Level.cpp moc_Mario.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Bullet.cpp moc_Enemy.cpp moc_Level.cpp moc_Mario.cpp moc_mainwindow.cpp
moc_Bullet.cpp: ../../Bullet.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QObject \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qobject.h \
		/Users/yassintawfik/Qt/6.8.2/macos/libexec/moc
	/Users/yassintawfik/Qt/6.8.2/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201402L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=17 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/macx-clang -I'/Users/yassintawfik/Desktop/supermariomohab/SuperMario real' -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/yassintawfik/Qt/6.8.2/macos/lib ../../Bullet.h -o moc_Bullet.cpp

moc_Enemy.cpp: ../../Enemy.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QObject \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qobject.h \
		/Users/yassintawfik/Qt/6.8.2/macos/libexec/moc
	/Users/yassintawfik/Qt/6.8.2/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201402L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=17 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/macx-clang -I'/Users/yassintawfik/Desktop/supermariomohab/SuperMario real' -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/yassintawfik/Qt/6.8.2/macos/lib ../../Enemy.h -o moc_Enemy.cpp

moc_Level.cpp: ../../Level.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QTimer \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		/Users/yassintawfik/Qt/6.8.2/macos/libexec/moc
	/Users/yassintawfik/Qt/6.8.2/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201402L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=17 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/macx-clang -I'/Users/yassintawfik/Desktop/supermariomohab/SuperMario real' -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/yassintawfik/Qt/6.8.2/macos/lib ../../Level.h -o moc_Level.cpp

moc_Mario.cpp: ../../Mario.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QObject \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qobject.h \
		../../Player.h \
		../../GameObject.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QKeyEvent \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/yassintawfik/Qt/6.8.2/macos/libexec/moc
	/Users/yassintawfik/Qt/6.8.2/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201402L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=17 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/macx-clang -I'/Users/yassintawfik/Desktop/supermariomohab/SuperMario real' -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/yassintawfik/Qt/6.8.2/macos/lib ../../Mario.h -o moc_Mario.cpp

moc_mainwindow.cpp: ../../mainwindow.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsView \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QLabel \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QTimer \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		../../Coin.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Player.h \
		../../GameObject.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QKeyEvent \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/yassintawfik/Qt/6.8.2/macos/libexec/moc
	/Users/yassintawfik/Qt/6.8.2/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201402L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=17 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/yassintawfik/Qt/6.8.2/macos/mkspecs/macx-clang -I'/Users/yassintawfik/Desktop/supermariomohab/SuperMario real' -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers -I/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/yassintawfik/Qt/6.8.2/macos/lib ../../mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ../../mainwindow.ui \
		/Users/yassintawfik/Qt/6.8.2/macos/libexec/uic
	/Users/yassintawfik/Qt/6.8.2/macos/libexec/uic ../../mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

Bullet.o: ../../Bullet.cpp ../../Bullet.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QObject \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qobject.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QTimer \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QList \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qlist.h \
		../../enemy.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		../../player.h \
		../../GameObject.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QKeyEvent \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bullet.o ../../Bullet.cpp

Coin.o: ../../Coin.cpp ../../Coin.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QBrush \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qbrush.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Coin.o ../../Coin.cpp

Enemy.o: ../../Enemy.cpp ../../Enemy.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QObject \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qobject.h \
		../../Player.h \
		../../GameObject.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QKeyEvent \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qevent.h \
		../../Bullet.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QPixmap \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qpixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Enemy.o ../../Enemy.cpp

GameObject.o: ../../GameObject.cpp ../../GameObject.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Player.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QKeyEvent \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameObject.o ../../GameObject.cpp

Level.o: ../../Level.cpp ../../Level.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QTimer \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		../../Mario.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QObject \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qobject.h \
		../../Player.h \
		../../GameObject.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QKeyEvent \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qevent.h \
		../../Coin.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		../../Enemy.h \
		../../Obstacle.h \
		../../Platform.h \
		../../PowerUp.h \
		../../PrincessPeach.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QFont \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qfont.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Level.o ../../Level.cpp

Mario.o: ../../Mario.cpp ../../mario.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QObject \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qobject.h \
		../../Player.h \
		../../GameObject.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QKeyEvent \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QPixmap \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qpixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mario.o ../../Mario.cpp

Obstacle.o: ../../Obstacle.cpp ../../Obstacle.h \
		../../GameObject.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Player.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QKeyEvent \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Obstacle.o ../../Obstacle.cpp

Platform.o: ../../Platform.cpp ../../Platform.h \
		../../GameObject.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QPixmap \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qpixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Platform.o ../../Platform.cpp

Player.o: ../../Player.cpp ../../Player.h \
		../../GameObject.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QKeyEvent \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qevent.h \
		../../Level.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QTimer \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		../../Coin.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		../../Enemy.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QObject \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qobject.h \
		../../Obstacle.h \
		../../Platform.h \
		../../PowerUp.h \
		../../PrincessPeach.h \
		../../Mario.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QList \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Player.o ../../Player.cpp

PowerUp.o: ../../PowerUp.cpp ../../PowerUp.h \
		../../GameObject.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Player.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QKeyEvent \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PowerUp.o ../../PowerUp.cpp

PrincessPeach.o: ../../PrincessPeach.cpp ../../PrincessPeach.h \
		../../GameObject.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Player.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QKeyEvent \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QFont \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qfont.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PrincessPeach.o ../../PrincessPeach.cpp

main.o: ../../main.cpp ../../MainWindow.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsView \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QLabel \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QTimer \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		../../Coin.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Player.h \
		../../GameObject.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QKeyEvent \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qevent.h \
		../../Level.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QApplication \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../../main.cpp

mainwindow.o: ../../mainwindow.cpp ../../mainwindow.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsView \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QLabel \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QTimer \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		../../Coin.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Player.h \
		../../GameObject.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QKeyEvent \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qevent.h \
		../../Mario.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QObject \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qobject.h \
		../../Bullet.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		../../Enemy.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/QFont \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtGui.framework/Headers/qfont.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QDebug \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qdebug.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/QList \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtCore.framework/Headers/qlist.h \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		/Users/yassintawfik/Qt/6.8.2/macos/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../../mainwindow.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

qrc_Resources3.o: qrc_Resources3.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Resources3.o qrc_Resources3.cpp

qrc_homepage.o: qrc_homepage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_homepage.o qrc_homepage.cpp

qrc_resources2.o: qrc_resources2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources2.o qrc_resources2.cpp

moc_Bullet.o: moc_Bullet.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Bullet.o moc_Bullet.cpp

moc_Enemy.o: moc_Enemy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Enemy.o moc_Enemy.cpp

moc_Level.o: moc_Level.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Level.o moc_Level.cpp

moc_Mario.o: moc_Mario.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Mario.o moc_Mario.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

